# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages
name: ðŸ“¦ Npm Package & Publish
env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  FORCE_COLOR: true

permissions: write-all
on:
  workflow_dispatch:

  push:
    tags:
      - "v*"

jobs:
  test:
    name: ðŸ“‹ Test on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js Environment
        uses: actions/setup-node@v3
        with:
          cache: npm
          cache-dependency-path: package-lock.json
          node-version-file: .nvmrc

      - name: Setup project
        run: npm ci

      - name: ðŸ“‹ Run Tests
        run: npm run test

  publish-npm:
    needs: test
    runs-on: ubuntu-latest
    name: ðŸšš Npm Publish
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js Environment
        uses: actions/setup-node@v3
        with:
          cache: npm
          cache-dependency-path: package-lock.json
          node-version-file: .nvmrc

      - name: Setup Project
        run: npm ci

      - name: ðŸ”¨ Compile Project
        run: npm run compile

      - name: ðŸšš Npm Publish
        run: npm publish
